### ISSUE TITLE
Valid JSON files not found

### ISSUE THREAD

**Issue by bboettcher3** [neesjanvaneck/VOSviewer-Online#16]
Hi, I'm developing a web app that hosts some VOSviewer JSON files and dynamically loads them into an iframe.
I can confirm that the target URLs return valid JSON networks (e.g., my web app's URL: https://musictechnet.simssa.ca/network?idx=30), but embedding the returned JSON into VOSviewer online returns "Error while reading VOSviewer JSON file: File cannot be found" (e.g., https://app.vosviewer.com/?json=https://musictechnet.simssa.ca/network?idx=30).

The previous link had been loaded correctly for most of the development process, but recently won't load any of the networks. I've tried returning a download of the JSON as well as just the JSON as you do in the VOSviewer Online doc examples, but neither are working anymore.

This issue has been intermittent throughout the development process, but recently none of the networks are loading anymore. I can also confirm that the JSONs loaded locally into VOSviewer online display the network perfectly. It's a pretty odd issue.

**Comment by neesjanvaneck** [comment]
Hi @bboettcher3, it seems that your JSON URL is not working properly. When I try the URL I receive a '502 Bad Gateway' error.

**Comment by bboettcher3** [comment]
Apologies, I was doing some work on the server. It should be working now!

**Comment by neesjanvaneck** [comment]
Thanks, the issue should be fixed! Could you test it on your side?

**Comment by bboettcher3** [comment]
Just did, it's working again, thanks so much! Could I ask what the issue was?

**Comment by neesjanvaneck** [comment]
Thanks for testing! There was an issue with validating peer certificates on the server.

BTW, nice visualization!
