### ISSUE TITLE
Serving VOSviewer-Online at custom path

### ISSUE THREAD

**Issue by gavieira** [neesjanvaneck/VOSviewer-Online#34]
Hi,

Is there a way to serve VOSviewer-Online (development version) at http://localhost:8600/vosviewer or some other custom path?

Thanks for the amazing tool!

**Comment by neesjanvaneck** [comment]
A simple approach to achieve this is to add the following in the devServer options in `webpack.config.babel.js`.

```
devServer: {
  //...
  proxy: {
    '/vosviewer': {
	  target: 'http://localhost:8600',
	  pathRewrite: { '^/vosviewer': '' },
    },
  },
}
```

See also the [webpack devServer.proxy documentation.](https://webpack.js.org/configuration/dev-server/#devserverproxy)

**Comment by gavieira** [comment]
Thanks for the help!

Actually, adding the devServer options did not work out for me, but changing the 'publicPath' option to "/vosviewer/" in the 'config.ouput' section of `webpack.config.babel.js` did the trick:

```
config.output = {
   //...
   publicPath: env.dev ? '/vosviewer/' : undefined,
   //...
};
```
Obs: The trailing forward slash in "/vosviewer/" was necessary to make it work as expected (i.e. correctly read files in 'data' dir at startup) behind my nginx reverse proxy.
