### ISSUE TITLE
Add metadata fields for network object and add these fields to the viz

### ISSUE THREAD

**Issue by seinecle** [neesjanvaneck/VOSviewer-Online#4]
Hi! Thanks for this great web app. I am trying to integrate it to https://nocodefunctions.com so that users can visualize the networks they build.

The json format is rich, and it could be useful to complement it with descriptive fields for the network. These fields would be parsed and fill in placeholders in the visualization. Either in a existing or new collapsable panel, or directly visible (especially for the title I would say?).

The same way there is a config object, there could be a "metadata" object with:

```
"metadata": {
            "author(s) of the visualization": " xxxxx",
            "date of creation": "xxxx",
            "description of the data": "xxxx",
            "title of the visualization": "xxxxxxx",
            "further information": "xxxxxxxx"
        }
```

**Comment by neesjanvaneck** [comment]
Thanks a lot for the suggestion. See #13 for the implementation.

The [VOSviewer JSON files](https://app.vosviewer.com/docs/file-types/json-file-type/) documentation has been updated accordingly.
