### ISSUE TITLE
odd zoom behaviour when using show_item parameter

### ISSUE THREAD

**Issue by paulmaxus** [neesjanvaneck/VOSviewer-Online#44]
I've observed that when using the URL parameter _show_item_=x, the app zooms in on a node labeled **y (x)** instead of the node labeled **x**. I'm not familiar with the function levenSort, but it seems intuitively right to select the first item returned by the sort (line referenced below), so I'm wondering why I see the behaviour described above. The Levenshtein distance should be 0 for the exact match and I assumed sortedItems[0] would then return x.

https://github.com/neesjanvaneck/VOSviewer-Online/blob/b09674ed08c5f4ded4b2be14cdd56dcddbc2be60/src/component.js#L209

**Comment by neesjanvaneck** [comment]
@paulmaxus  Could you please share an example that reproduces this issue? Thanks in advance!

**Comment by paulmaxus** [comment]
@neesjanvaneck Yes, of course.
One example can be found in the citation network of journals example in the vosviewer docs.
When I use the parameter _physical review_ the app zooms in on _biophysical reviews_ instead on for instance _physical review b_ which should have the smaller distance.

https://app.vosviewer.com/?json=https%3A%2F%2Fapp.vosviewer.com%2Fdata%2FCrossref_journal_citation_network_10000.json&show_item=physical%20review

**Comment by neesjanvaneck** [comment]
Thanks again for reporting this issue @paulmaxus. I have fixed the issue in [release 1.2.4](https://github.com/neesjanvaneck/VOSviewer-Online/releases/tag/1.2.4).
