### ISSUE TITLE
Computing the network layout online ?

### ISSUE THREAD

**Issue by ericjeangirard** [neesjanvaneck/VOSviewer-Online#49]
Hello
From what I understand, the VOSviewer online can render a network that was first computed by the VOS viewer.
It would be very interesting to be able to compute the network layout directly in the web application, without using an heavy client.
I did not found an implementation of the VOS algorithm. The link  www.neesjanvaneck.nl/vos/ that appears in the original publication does not point to a "simple open source program" but to the VOSviewer website.

**Comment by neesjanvaneck** [comment]
Hi @ericjeangirard,

Like the stand-alone VOSviewer, VOSviewer Online can also be used to generate new network layout and clustering solutions. Both tools use the [Leiden algorithm](https://doi.org/10.1038/s41598-019-41695-z) for network clustering and the [VOS technique](https://doi.org/10.1002/asi.21421) for network layout.

A Java implementation of these layout and clustering algorithms can be found in the [networkanalysis](https://github.com/CWTSLeiden/networkanalysis) package. This package is used by the stand-alone VOSviewer.

A Typescript implementation of the algorithms can be found in the [networkanalysis-ts](https://www.npmjs.com/package/networkanalysis-ts) package. This package is a TypeScript port of the [networkanalysis](https://github.com/CWTSLeiden/networkanalysis) package written in Java and that is used by VOSviewer Online.
