### ISSUE TITLE
Issue with tiny url

### ISSUE THREAD

**Issue by t-b-p** [neesjanvaneck/VOSviewer-Online#50]
Hi,

I have issues with sharing links on VosViewer Online.

It does not seem like tinyurls/QR codes are correctly interpreted in terms of the input path/token to the json files in my Google Drive (all json files are shared read-only). It worked four weeks ago. 

How do I resolve this so I can share my networks?

Best,
Tobias

**Comment by t-b-p** [comment]
PS. I have tested the tinyurls directing to VosViewer. They seem to be correct (hexadecimal encoding included). I can see and download my json-files perfectly fine, VosViewer does not.

**Comment by t-b-p** [comment]
Update: My links to VosViewer are now working. What could cause the issue above?

**Comment by neesjanvaneck** [comment]
Thanks for reporting this issue @t-b-p. I'm not entirely sure what caused the problem. It is possible that Google had temporarily blocked VOSviewer Online's access for some reason. Good to hear that the problem was resolved quickly and that everything is working as intended again.
