### ISSUE TITLE
Proxy Config

### ISSUE THREAD

**Issue by geraldo-leite** [neesjanvaneck/VOSviewer-Online#51]
Hi, I'm trying to use the viewing features through Google Drive using a dev app, but I'm running into a problem with the proxy server configuration (Error while reading VOSviewer JSON data: Re-select the file.), can you help me resolve this?

**Comment by neesjanvaneck** [comment]
Hi @geraldo-leite, viewing externally stored visualization files is not supported in the development evironment.
