### ISSUE TITLE
Can't use items templates with the VOSviewer-Online component in Vite app

### ISSUE THREAD

**Issue by ahonestla** [neesjanvaneck/VOSviewer-Online#53]
### Description
I'm trying to use the [vosviewer-online component](https://www.npmjs.com/package/vosviewer-online) within a vite typescript application. 

Everything works fine with a standard network. 
However if I add items descriptions or templates descriptions, the application crashes when I hover a node with the following error : 
```
react-dom.development.js:26923  Uncaught TypeError: (0 , ju.addHook) is not a function
    at du (helpers2.js:42:3)
    at y2 (index.js:175:40)
    at index.js:193:22
    at observer.ts:104:34
    at useObserver.ts:126:25
    at trackDerivedFunction (derivation.ts:183:24)
    at Reaction2.track (reaction.ts:137:24)
    at useObserver (useObserver.ts:124:18)
    at observerComponent (observer.ts:104:16)
    at renderWithHooks (react-dom.development.js:16305:18)
```

The npm run build displays the following error that may be the cause : 
```
vite v5.0.11 building for production...
node_modules/vosviewer-online/index.js (139:115203) "addHook" is not exported by "node_modules/dompurify/dist/purify.es.js", imported by "node_modules/vosviewer-online/index.js".
node_modules/vosviewer-online/index.js (139:115226) "sanitize" is not exported by "node_modules/dompurify/dist/purify.es.js", imported by "node_modules/vosviewer-online/index.js".
```

Do you have any suggestions or workaround ? 
Thanks in advance.

PS: Note that the items descriptions works fine in a standard react typescript app without vite.

### Reproduction

I made a repo with a vite template that you can build.
https://github.com/ahonestla/vosviewer-online-component-vite

Use _JOI_2007-2016_co-authorship_network.json_ for the default network and _JOI_2007-2016_co-authorship_network_template.json_ for the network with items descriptions.

**Comment by neesjanvaneck** [comment]
Thanks for reporting this issue @ahonestla. I have fixed the issue in release [1.2.2](https://github.com/neesjanvaneck/VOSviewer-Online/releases/tag/1.2.2). See #57 for the implementation.
