### ISSUE TITLE
Clusters labels size with low resolution issue

### ISSUE THREAD

**Issue by ahonestla** [neesjanvaneck/VOSviewer-Online#61]
Hello,

I'm using the the [vosviewer-online component](https://www.npmjs.com/package/vosviewer-online) within a vite typescript application.

The clusters labels in the legend and the legend box have sometimes a disproportionate size.
It seems to depends to the resolution of the screen.

I did some tests with the exact same page : 
1. On my windows machine
- 1536 x 864 (and lower) : 
![image](https://github.com/neesjanvaneck/VOSviewer-Online/assets/111356254/eaea3d71-4556-485a-9dfe-8aca815158cd)
- 1920 x 1080 : 
![image](https://github.com/neesjanvaneck/VOSviewer-Online/assets/111356254/1d1aba7b-639b-47a4-addc-2e09bd13a563)

2. On my mac
- 1680 x 1050 (and lower) :
![image](https://github.com/neesjanvaneck/VOSviewer-Online/assets/111356254/33cc433f-509f-4f2f-bf6b-4654b41bed95)
- 2048 x 1280 :  
![image](https://github.com/neesjanvaneck/VOSviewer-Online/assets/111356254/ad83682e-ea7d-4798-8782-0ddb8386abd2)

What could be the cause for this behavior ?
Thank in advance!

**Comment by neesjanvaneck** [comment]
Thanks for reporting this issue @ahonestla. I have fixed the issue in [release 1.2.3](https://github.com/neesjanvaneck/VOSviewer-Online/releases/tag/1.2.3). See #63 for the implementation.
