### ISSUE TITLE
Node labels don't render correctly with HTML 

### ISSUE THREAD

**Issue by lambdamusic** [neesjanvaneck/VOSviewer-Online#65]
Hello :-) 

Can we add HTML to the id and labels? 

My data looks this: 

```json
      {
        "id": "<strong>Commissioning of the ATLAS Muon Spectrometer with cosmic rays</strong><br />European Physical Journal C ",
        "label": "<strong>Commissioning of the ATLAS Muon Spectrometer with cosmic rays</strong><br />European Physical Journal C ",
        "scores": {
          "_": 1
        },
        "weights": {},
        "cluster": 1,
        "url": "https://app.dimensions.ai/details/publication/pub.1012859014",
        "description": "<div class='description_heading'><a href='https://app.dimensions.ai/details/publication/pub.1012859014' target='_blank'><strong>Commissioning of the ATLAS Muon Spectrometer with cosmic rays</strong><br />European Physical Journal C </a></div>"
      },
```

But the resulting visualization is not rendering correctly:

![image](https://github.com/neesjanvaneck/VOSviewer-Online/assets/3493663/fd64a7df-fd38-4425-beef-25c88e1e0eb0)

Full JSON data here: [test.json](https://github.com/neesjanvaneck/VOSviewer-Online/files/14665396/test.json)

**Comment by neesjanvaneck** [comment]
Hi @lambdamusic! Currently, HTML tags are not supported in the id and label fields. Only descriptions can be formatted with HTML tags.

**Comment by neesjanvaneck** [comment]
Hi @lambdamusic. HTML tags are now automatically stripped from item labels, ensuring clean visualizations. This change also fixed an issue with the find functionality.
